[package]
name = "provenact-spec-validate"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
anyhow.workspace = true
provenact-spec-rs = { path = "../provenact-spec-rs" }
jsonschema.workspace = true
serde_json.workspace = true
serde_yaml.workspace = true
