[package]
name = "inactu-spec-rs"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
hex.workspace = true
serde.workspace = true
serde_json.workspace = true
serde_jcs.workspace = true
sha2.workspace = true
thiserror.workspace = true
