[package]
name = "inactu-spec-validate"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
anyhow.workspace = true
inactu-spec-rs = { path = "../inactu-spec-rs" }
jsonschema.workspace = true
serde_json.workspace = true
serde_yaml.workspace = true
